import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, ActivityIndicator } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { Colors } from '../../constants/Colors';

const SAMPLE_REPORT = `THREAT ASSESSMENT SUMMARY
─────────────────────────────────

RISK LEVEL: HIGH

CRITICAL FINDINGS:
• 1 unrecognized network device at 192.168.1.44
• 1 high-severity mobile configuration profile detected
• Meta SDK tracker with ad attribution capabilities

MODERATE FINDINGS:
• 2 medium-risk trackers (crash reporter, analytics)
• 1 suspicious cache database

NETWORK:
• 3 devices detected on LAN
• 1 flagged as unrecognized

RF ENVIRONMENT:
• 2 cell towers in range
• 1 tower marked for review (LTE B66)
• 1 unknown GSM 850 tower — potential IMSI catcher risk

RECOMMENDATIONS:
1. Review and remove profile.mobileconfig immediately
2. Investigate device at 192.168.1.44
3. Audit apps with active tracker SDKs
4. Verify legitimacy of GSM 850 tower in your area

Generated by Phone Invasion AI Engine`;

export default function ReportScreen() {
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState<string | null>(null);

  const generateReport = async () => {
    setLoading(true);
    await new Promise((r) => setTimeout(r, 1800));
    setReport(SAMPLE_REPORT);
    setLoading(false);
  };

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <Ionicons name="document-text" size={20} color={Colors.blue} />
        <Text style={styles.title}>AI Report</Text>
      </View>
      <ScrollView contentContainerStyle={styles.scroll}>
        {!report && !loading && (
          <View style={styles.emptyState}>
            <Ionicons name="analytics" size={56} color={Colors.border} />
            <Text style={styles.emptyTitle}>No Report Generated</Text>
            <Text style={styles.emptySubtitle}>Run a scan first, then generate your AI threat report.</Text>
          </View>
        )}

        {loading && (
          <View style={styles.emptyState}>
            <ActivityIndicator size="large" color={Colors.blue} />
            <Text style={styles.loadingText}>Analysing threat data…</Text>
          </View>
        )}

        {report && !loading && (
          <View style={styles.reportBox}>
            <Text style={styles.reportText}>{report}</Text>
          </View>
        )}

        <TouchableOpacity
          style={[styles.button, loading && styles.buttonDisabled]}
          onPress={generateReport}
          disabled={loading}
          activeOpacity={0.8}
        >
          <Ionicons name="sparkles" size={18} color="#000" />
          <Text style={styles.buttonText}>{report ? 'Regenerate Report' : 'Generate AI Report'}</Text>
        </TouchableOpacity>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 20, borderBottomWidth: 1, borderBottomColor: Colors.border },
  title: { fontSize: 18, fontWeight: '700', color: Colors.textPrimary },
  scroll: { padding: 20, gap: 20, flexGrow: 1 },
  emptyState: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12, paddingVertical: 60 },
  emptyTitle: { fontSize: 18, fontWeight: '600', color: Colors.textSecondary },
  emptySubtitle: { fontSize: 13, color: Colors.textMuted, textAlign: 'center', maxWidth: 240 },
  loadingText: { fontSize: 14, color: Colors.textSecondary, marginTop: 12 },
  reportBox: {
    backgroundColor: Colors.surfaceElevated,
    borderRadius: 10,
    padding: 18,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  reportText: { color: Colors.green, fontSize: 13, fontFamily: 'monospace', lineHeight: 20 },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Colors.blue,
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 8,
  },
  buttonDisabled: { opacity: 0.5 },
  buttonText: { color: '#000', fontWeight: '700', fontSize: 15 },
});
